name: graph_mixup
channels:
  - pytorch
  - pyg
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.1.0=pyhd8ed1ab_0
  - aiohappyeyeballs=2.4.0=pyhd8ed1ab_0
  - aiohttp=3.10.5=py311h61187de_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alembic=1.14.0=pyhd8ed1ab_0
  - alsa-lib=1.2.12=h4ab18f5_0
  - anyio=4.6.2=py311h06a4308_0
  - aom=3.9.1=hac33072_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h5eee18b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py311h06a4308_0
  - async-timeout=4.0.3=py311h06a4308_0
  - atk-1.0=2.36.0=ha1a6a79_0
  - attrs=24.2.0=pyh71513ae_0
  - babel=2.11.0=py311h06a4308_0
  - beautifulsoup4=4.12.3=py311h06a4308_0
  - black=24.8.0=py311h06a4308_0
  - blackd=24.8.0=hd8ed1ab_1
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottle=0.12.23=pyhd8ed1ab_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py311hb755f60_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.33.0=ha66036c_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cairo=1.18.0=hebfffa5_3
  - certifi=2025.1.31=py311h06a4308_0
  - cffi=1.17.0=py311ha8e6434_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=py311h06a4308_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorlog=6.8.2=py311h38be061_0
  - comm=0.2.1=py311h06a4308_0
  - contourpy=1.2.1=py311h9547e67_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.6.37=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.6=3
  - cycler=0.12.1=pyhd8ed1ab_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - double-conversion=3.3.0=h59595ed_0
  - easydict=1.9=py_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.2=h59595ed_0
  - ffmpeg=7.0.2=gpl_hebc05b9_101
  - filelock=3.15.4=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.53.1=py311h61187de_0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.4.1=py311h459d7ec_0
  - fsspec=2024.3.1=py311h06a4308_0
  - gdk-pixbuf=2.42.12=hb9ae30d_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - glib=2.80.3=h315aac3_2
  - glib-tools=2.80.3=h8fdd7da_2
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py311hc4f1f91_1
  - gnutls=3.8.7=h32866dd_0
  - gobject-introspection=1.78.1=py311h42194e9_2
  - graphite2=1.3.13=h59595ed_1003
  - graphviz=2.50.0=h78e8752_4
  - greenlet=3.0.3=py311hb755f60_0
  - grpcio=1.62.2=py311ha6695c7_0
  - gtk2=2.24.33=h27e1c3a_3
  - gts=0.7.6=hb67d8dd_3
  - h11=0.14.0=py311h06a4308_0
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=9.0.0=hda332d3_1
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.2=py311h06a4308_0
  - httpx=0.27.0=py311h06a4308_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.7=pyhd8ed1ab_0
  - importlib-metadata=8.3.0=pyha770c72_0
  - importlib_resources=6.4.3=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.29.5=py311h06a4308_0
  - ipython=8.27.0=py311h06a4308_0
  - jedi=0.19.1=py311h06a4308_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - json5=0.9.25=py311h06a4308_0
  - jsonschema=4.23.0=py311h06a4308_0
  - jsonschema-specifications=2023.7.1=py311h06a4308_0
  - jupyter-lsp=2.2.0=py311h06a4308_0
  - jupyter_client=8.6.0=py311h06a4308_0
  - jupyter_core=5.7.2=py311h06a4308_0
  - jupyter_events=0.10.0=py311h06a4308_0
  - jupyter_server=2.14.1=py311h06a4308_0
  - jupyter_server_terminals=0.4.4=py311h06a4308_1
  - jupyterlab=4.2.5=py311h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py311h06a4308_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py311h9547e67_1
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.2=cxx17_he02047a_1
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libass=0.17.3=h1dc1e6a_0
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=12_linux64_mkl
  - libclang-cpp18.1=18.1.8=default_hf981a13_2
  - libclang13=18.1.8=default_h9def88c_2
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.11.0.15=0
  - libcups=2.3.3=h4637d8d_4
  - libcurand=10.3.7.37=0
  - libcurl=8.9.1=hdb1bdb2_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.21=h4bc722e_0
  - libdrm=2.4.122=h4ab18f5_0
  - libedit=3.1.20191231=he28a2e2_2
  - libegl=1.7.0=ha4b6fd6_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgd=2.3.3=hd3e95f3_10
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran-ng=14.1.0=h69a702a_0
  - libgfortran5=14.1.0=hc5f4f2c_0
  - libgl=1.7.0=ha4b6fd6_0
  - libglib=2.80.3=h315aac3_2
  - libglvnd=1.7.0=ha4b6fd6_0
  - libglx=1.7.0=ha4b6fd6_0
  - libgomp=14.1.0=h77fa898_1
  - libgrpc=1.62.2=h15f2491_0
  - libhwloc=2.11.1=default_hecaa2ac_1000
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=12_linux64_mkl
  - libllvm18=18.1.8=h8b73ec9_2
  - libnghttp2=1.58.0=h47da74e_1
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopenvino=2024.3.0=h2da1b83_0
  - libopenvino-auto-batch-plugin=2024.3.0=hb045406_0
  - libopenvino-auto-plugin=2024.3.0=hb045406_0
  - libopenvino-hetero-plugin=2024.3.0=h5c03a75_0
  - libopenvino-intel-cpu-plugin=2024.3.0=h2da1b83_0
  - libopenvino-intel-gpu-plugin=2024.3.0=h2da1b83_0
  - libopenvino-intel-npu-plugin=2024.3.0=h2da1b83_0
  - libopenvino-ir-frontend=2024.3.0=h5c03a75_0
  - libopenvino-onnx-frontend=2024.3.0=h07e8aee_0
  - libopenvino-paddle-frontend=2024.3.0=h07e8aee_0
  - libopenvino-pytorch-frontend=2024.3.0=he02047a_0
  - libopenvino-tensorflow-frontend=2024.3.0=h39126c6_0
  - libopenvino-tensorflow-lite-frontend=2024.3.0=he02047a_0
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.43=h2797004_0
  - libpq=16.4=h482b261_0
  - libprotobuf=4.25.3=h08a7969_0
  - libre2-11=2023.09.01=h5a48ba9_2
  - librsvg=2.58.4=hc0ffecb_0
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.6.0=h46a8edc_4
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=hb711507_0
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.16=hd590300_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h2c5496b_1
  - libxml2=2.12.7=he7c6b58_4
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=h4ab18f5_1
  - lightning=2.4.0=pyhd8ed1ab_0
  - lightning-utilities=0.11.6=pyhd8ed1ab_0
  - llvm-openmp=15.0.7=h0cdce71_0
  - mako=1.3.5=pyhd8ed1ab_0
  - mariadb=1.1.10=py311hfdbb021_6
  - mariadb-connector-c=3.4.1=h59f47de_1
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.5=py311h459d7ec_0
  - matplotlib=3.9.2=py311h38be061_0
  - matplotlib-base=3.9.2=py311h74b4f7c_0
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - mistune=2.0.4=py311h06a4308_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py311h5eee18b_0
  - mkl_fft=1.3.1=py311h30b3d60_0
  - mkl_random=1.2.2=py311hba01205_0
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.1=h38ae2d0_2
  - mpmath=1.3.0=pyhd8ed1ab_0
  - multidict=6.0.5=py311h459d7ec_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy=1.13.0=py311h9ecbd09_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - mysql-common=9.0.1=h70512c7_0
  - mysql-connector-python=9.0.0=py311h9c9ff8c_1
  - mysql-libs=9.0.1=ha479ceb_0
  - mysqlclient=2.2.4=py311hfdbb021_3
  - nbclient=0.8.0=py311h06a4308_0
  - nbconvert=7.16.4=py311h06a4308_0
  - nbformat=5.10.4=py311h06a4308_0
  - ncurses=6.5=h59595ed_0
  - nest-asyncio=1.6.0=py311h06a4308_0
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.4.2=pyh267e887_2
  - ninja=1.12.1=h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - notebook=7.2.2=py311h06a4308_1
  - notebook-shim=0.2.3=py311h06a4308_0
  - numpy=1.24.3=py311hc206e33_0
  - numpy-base=1.24.3=py311hfd5febd_0
  - ocl-icd=2.3.2=hd590300_1
  - openh264=2.4.1=h59595ed_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.3.2=hb9d3cd8_0
  - optuna=3.6.1=pyhd8ed1ab_0
  - optuna-dashboard=0.16.0=pyhd8ed1ab_0
  - optuna-integration=3.6.0=pyhd8ed1ab_0
  - overrides=7.4.0=py311h06a4308_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py311h14de704_1
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pango=1.54.0=h4c5309f_1
  - parso=0.8.3=pyhd3eb1b0_0
  - pathspec=0.10.3=py311h06a4308_0
  - pcre2=10.44=hba22ea6_2
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=10.4.0=py311h82a398c_0
  - pip=24.2=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - platformdirs=3.10.0=py311h06a4308_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - pot=0.9.4=py311h14de704_0
  - prometheus_client=0.21.0=py311h06a4308_0
  - prompt-toolkit=3.0.43=py311h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - protobuf=4.25.3=py311h7b78aeb_0
  - psutil=6.0.0=py311h331c9d8_0
  - psycopg2=2.9.9=py311h03dec38_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pugixml=1.14=h59595ed_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pyflakes=3.2.0=py311h06a4308_0
  - pyg=2.5.2=py311_torch_2.2.0_cu121
  - pygments=2.15.1=py311h06a4308_1
  - pygmtools=0.5.3=pyhd8ed1ab_0
  - pygraphviz=1.14=py311h5eee18b_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyside6=6.7.2=py311hba19f1e_2
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=8.3.2=pyhd8ed1ab_0
  - python=3.11.9=hb806964_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-dotenv=0.21.0=py311h06a4308_0
  - python-fastjsonschema=2.20.0=py311h06a4308_0
  - python-json-logger=2.0.7=py311h06a4308_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.11=5_cp311
  - pytorch=2.2.2=py3.11_cuda12.1_cudnn8.9.2_0
  - pytorch-cluster=1.6.3=py311_torch_2.2.0_cu121
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-lightning=2.4.0=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.1.2=py311_torch_2.2.0_cu121
  - pytorch-sparse=0.6.18=py311_torch_2.2.0_cu121
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h61187de_0
  - pyzmq=25.1.2=py311h6a678d5_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.7.2=hb12f9c5_5
  - re2=2023.09.01=h7f4b329_2
  - readline=8.2=h8228510_1
  - referencing=0.30.2=py311h06a4308_0
  - requests=2.32.3=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=py311h06a4308_0
  - rfc3986-validator=0.1.1=py311h06a4308_0
  - rpds-py=0.10.6=py311hb02cf49_0
  - ruff=0.7.0=py311hef32070_0
  - scikit-learn=1.5.1=py311hd632256_0
  - scipy=1.14.0=py311h0a5b728_2
  - send2trash=1.8.2=py311h06a4308_0
  - setuptools=72.2.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.1=ha2e4443_0
  - sniffio=1.3.0=py311h06a4308_0
  - soupsieve=2.5=py311h06a4308_0
  - sqlalchemy=2.0.32=py311h61187de_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - svt-av1=2.1.2=hac33072_0
  - sympy=1.13.2=pypyh2585a3b_103
  - tbb=2021.12.0=h434a139_3
  - tensorboard=2.17.1=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py311h63ff55d_1
  - terminado=0.17.1=py311h06a4308_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tinycss2=1.2.1=py311h06a4308_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.1=pyhd8ed1ab_0
  - torchaudio=2.2.2=py311_cu121
  - torchmetrics=1.4.0.post0=pyhd8ed1ab_0
  - torchtriton=2.2.0=py311
  - torchvision=0.17.2=py311_cu121
  - tornado=6.4.1=py311h331c9d8_0
  - tqdm=4.66.5=pyhd8ed1ab_0
  - traitlets=5.14.3=py311h06a4308_0
  - types-pyyaml=6.0.12.12=py311h06a4308_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - urllib3=2.2.2=pyhd8ed1ab_1
  - wayland=1.23.0=h5291e77_0
  - wayland-protocols=1.36=hd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311h06a4308_1
  - websocket-client=1.8.0=py311h06a4308_0
  - werkzeug=3.0.3=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.4=h4ab18f5_2
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=hb711507_1
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h4bc722e_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxtst=1.2.5=h4bc722e_0
  - xorg-libxxf86vm=1.1.5=hb9d3cd8_2
  - xorg-recordproto=1.14.2=hb9d3cd8_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.4=py311h459d7ec_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.20.0=pyhd8ed1ab_0
  - zlib=1.3.1=h4ab18f5_1
  - zstandard=0.23.0=py311h5cd10c7_0
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - build==1.2.2.post1
      # - graph-exporter==0.0.1
      - pyproject-hooks==1.2.0
prefix: /home/user/miniconda3/envs/graph_mixup
